# Generated by Django 4.2 on 2024-10-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(db_index=True, max_length=50)),
                ("symbol", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name_plural": "Currencies",
            },
        ),
    ]
