# Generated by Django 4.2 on 2024-10-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={},
        ),
    ]
