# Generated by Django 4.2 on 2024-10-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0002_alter_currency_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name_plural": "Currencies"},
        ),
    ]
