# Generated by Django 4.2 on 2024-10-06 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valuation_date", models.DateField(db_index=True)),
                (
                    "rate_value",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=18),
                ),
                ("provider", models.CharField(max_length=100)),
                (
                    "exchanged_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="currency.currency",
                    ),
                ),
                (
                    "source_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchanges",
                        to="currency.currency",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    (
                        "source_currency",
                        "exchanged_currency",
                        "valuation_date",
                        "provider",
                    )
                },
            },
        ),
    ]
