# Generated by Django 4.2 on 2024-10-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="currencyexchangerate",
            name="priority",
            field=models.IntegerField(default=1),
        ),
    ]
