# Generated by Django 4.2 on 2024-10-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0002_currencyexchangerate_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="currencyexchangerate",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
